# 4 TO - DO - **Task**

# 4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:

In [1]:
import numpy as np

In [24]:
A = np.empty((2,2))
B = np.ones((4,2))
print(A)
print(B)

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
fill_value = 7
C = np.full((3, 3), fill_value, dtype=float)
D = np.zeros_like(C)
E = np.ones_like(C)
print(C)
print(D)
print(E)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
new_list = [1,2,3,4]
F = np.array(new_list)
print(F)

[1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [26]:
G = np.arange(10, 50)
print(G)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
H = np.arange(9).reshape((3, 3))
print(H)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
J = np.random.random(30)
print(J)
print(J.mean())

[0.08592479 0.06913657 0.18997889 0.41103475 0.48238466 0.01727722
 0.1407697  0.9227469  0.03032033 0.3110793  0.97081821 0.27870634
 0.06274331 0.2060813  0.57185348 0.6278827  0.98350447 0.8419081
 0.41604231 0.80825621 0.65728364 0.47412089 0.6482113  0.83990528
 0.64018123 0.99996412 0.54439907 0.19807041 0.23871052 0.97749404]
0.48822633413099464


In [44]:
K = np.random.random((10, 10))
print(K)
print(f"Max: {K.max()}")
print(f"Max: {K.min()}")

[[0.77976582 0.84397024 0.12528165 0.37069274 0.22603029 0.87719258
  0.76874609 0.87310069 0.00613679 0.76625667]
 [0.58358428 0.41335654 0.38697269 0.36090709 0.38115222 0.71124119
  0.42081709 0.13613403 0.49690893 0.78908871]
 [0.82002803 0.94688482 0.33885119 0.5848673  0.51401215 0.54560187
  0.50435552 0.13125489 0.35830007 0.31486426]
 [0.78612193 0.38156582 0.85580425 0.75683508 0.57508143 0.94487421
  0.95618254 0.06215848 0.14056012 0.84373873]
 [0.62780114 0.94354603 0.57182707 0.4574936  0.46359196 0.2622714
  0.28832489 0.23497239 0.04732635 0.67936133]
 [0.02673898 0.68086515 0.73957894 0.83606796 0.52195311 0.51737227
  0.23380752 0.51110387 0.88108541 0.5374698 ]
 [0.97925859 0.37997438 0.26991261 0.67925296 0.63194068 0.90132652
  0.91518696 0.75362784 0.75648988 0.86254731]
 [0.66268904 0.9603853  0.44293955 0.42033896 0.91000575 0.81918327
  0.9483327  0.67323743 0.17059495 0.94105697]
 [0.49930028 0.0099535  0.16026872 0.48774179 0.40854077 0.32545793
  0.30370283 

In [47]:
L = np.zeros(10)
L[4] = 1
print(L)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [51]:
M = [1,2,0,0,4,0]
print(M[::-1])

[0, 4, 0, 0, 2, 1]


In [60]:
N = np.ones((5, 5))
N[1:-1, 1:-1] = 0
print(N)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [63]:
O = (np.indices((8, 8)).sum(axis=0) % 2)
print(O)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Problem - 3: Array Operations:

In [76]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [69]:
print(x + y)
print(v + w)

[[ 6  8]
 [10 13]]
[20 22]


In [70]:
print(x - y)
print(v - w)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [71]:
print(2*x)
print(2*y)
print(2*v)
print(2*w)

[[ 2  4]
 [ 6 10]]
[[10 12]
 [14 16]]
[18 20]
[22 24]


In [72]:
print(x**2)
print(y**2)
print(v**2)
print(w**2)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


In [77]:
print(np.dot(v, w))
print(np.dot(x, v))
print(np.dot(x, y))

219
[29 77]
[[19 22]
 [50 58]]


In [82]:
print(np.hstack((x, y)))
print(np.vstack((v, w)))

[[1 2 5 6]
 [3 5 7 8]]
[[ 9 10]
 [11 12]]


In [84]:
try:
    xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Problem - 4: Matrix Operations:

In [103]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inverse = np.linalg.inv(A)
A_transpose = np.transpose(A)
B_transpose = np.transpose(B)
I = np.eye(2)

In [99]:
if np.allclose((A @ A_inverse), I):
  print("A.A−1 = I. proved")

A.A−1 = I. proved


In [101]:
if not np.allclose((A @ B), (B @ A)):
  print("AB ̸= BA. proved")

AB ̸= BA. proved


In [104]:
if np.allclose(np.transpose(A @ B), (B_transpose @ A_transpose)):
  print("(Transpose of (AB)) == (transpose of B * Transpose of A) proved")

(Transpose of (AB)) == (transpose of B * Transpose of A) proved


In [105]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

B = np.array([-1, -3, 9])

In [107]:
X = np.linalg.inv(A) @ B
print(X)

[ 2.  1. -2.]


In [108]:
np.linalg.solve(A, B)

array([ 2.,  1., -2.])

# **4.2 Experiment: How Fast is Numpy?**

In [130]:
import time
import random

In [110]:
size = 1_000_000

list1 = list(range(size))
list2 = list(range(size))

arr1 = np.array(list1)
arr2 = np.array(list2)


In [114]:
start = time.time()

result_list = [list1[i] + list2[i] for i in range(size)]

end = time.time()
print("Time taken using Python lists for element-wise addition:", end - start, "seconds")

Time taken using Python lists: 0.36597323417663574 seconds


In [115]:
start = time.time()

result_array = arr1 + arr2

end = time.time()
print("Time taken using NumPy arrays for element-wise addition:", end - start, "seconds")

Time taken using NumPy arrays: 0.00905919075012207 seconds


In [123]:
start = time.time()

result_list = [list1[i] * list2[i] for i in range(size)]

end = time.time()
print("Time taken using Python lists for element-wise multiplication:", end - start, "seconds")

Time taken using Python lists for element-wise multiplication: 0.12710022926330566 seconds


In [124]:
start = time.time()

result_array = arr1 * arr2

end = time.time()
print("Time taken using NumPy arrays for element-wise multiplication:", end - start, "seconds")

Time taken using NumPy arrays for element-wise multiplication: 0.0029799938201904297 seconds


In [127]:
start = time.time()

result_list = sum(list1[i] * list2[i] for i in range(size))

end = time.time()
print("Time taken using Python lists for dot product:", end - start, "seconds")

Time taken using Python lists for dot product: 0.21853971481323242 seconds


In [128]:
start = time.time()

result_array = np.dot(arr1, arr2)

end = time.time()
print("Time taken using NumPy arrays for dot product:", end - start, "seconds")


Time taken using NumPy arrays for dot product: 0.002674102783203125 seconds


In [132]:
size = 1000

matrix1 = [[random.randint(0, 10) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(0, 10) for _ in range(size)] for _ in range(size)]

arr1 = np.array(matrix1)
arr2 = np.array(matrix2)

In [133]:
start = time.time()

result_list = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result_list[i][j] += matrix1[i][k] * matrix2[k][j]

end = time.time()
print("Time taken using Python lists for matrix multiplication:", end - start, "seconds")

Time taken using Python lists for matrix multiplication: 302.5201086997986 seconds


In [135]:
start = time.time()

result_array = arr1 @ arr2

end = time.time()
print("Time taken using NumPy arrays for matrix multiplication:", end - start, "seconds")

Time taken using NumPy arrays for matrix multiplication: 2.223238229751587 seconds
